### ISSUE TITLE
Conflicting dependency aiohttp 

### ISSUE THREAD

**Issue by SufiyanGolandaz** [voxos-ai/bolna#106]
Unable to setup locally due to conflicting dependency caused by aiohttp library.

162.5 ERROR: Cannot install twilio because these package versions have conflicting dependencies.
162.5
162.5 The conflict is caused by:
162.5     aiohttp 3.9.3 depends on multidict<7.0 and >=4.5
162.5     aiohttp 3.9.2 depends on multidict<7.0 and >=4.5
162.5     aiohttp 3.9.1 depends on multidict<7.0 and >=4.5
162.5     aiohttp 3.9.0 depends on multidict<7.0 and >=4.5
162.5     aiohttp 3.8.6 depends on multidict<7.0 and >=4.5
162.5     aiohttp 3.8.5 depends on multidict<7.0 and >=4.5
162.5     aiohttp 3.8.4 depends on multidict<7.0 and >=4.5

**Comment by prateeksachan** [comment]
Please check using a `virtualenv`. Feel free to re-open it.
