### ISSUE TITLE
Issue Related after build due to new changes : git+https://github.com/qdrant/fastembed

### ISSUE THREAD

**Issue by orion-satyammishra** [voxos-ai/bolna#128]
3.839       setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
3.839           git+https://github.com/qdrant/fastembed

**Comment by orion-satyammishra** [comment]
Need to remove this from requirements.txt

**Comment by prateeksachan** [comment]
@orion-satyammishra have fixed the package version issue in https://github.com/bolna-ai/bolna/pull/129. Can you now check once?

**Comment by orion-satyammishra** [comment]
@prateeksachan  it is not fixed           
git+https://github.com/qdrant/fastembed@master
4.434              ^
4.434       [end of output]
4.434
4.434   note: This error originates from a subprocess, and is likely not a problem with pip.
4.436 error: subprocess-exited-with-error
4.436

**Comment by prateeksachan** [comment]
@orion-satyammishra can you please tell your OS & it's version?

**Comment by orion-satyammishra** [comment]
OS: Mac OS Sonama 14.4.1 (23E224)
MacBook Air M1

Also we are facing same issue in window and linux machines

**Comment by prateeksachan** [comment]
@orion-satyammishra I had committed the branch tag as `master` instead of `main`. Have again pushed the changes in https://github.com/bolna-ai/bolna/pull/130. Can you try again once?

**Comment by orion-satyammishra** [comment]
.832           git+https://github.com/qdrant/fastembed@main
3.832              ^
3.832       [end of output]
3.832
3.832   note: This error originates from a subprocess, and is likely not a problem with pip.
3.832 error: subprocess-exited-with-error
3.832
3.832 × Getting requirements to build wheel did not run successfully.
3.832 │ exit code: 1
3.832 ╰─> See above for output.
3.832
3.832 note: This error originates from a subprocess, and is likely not a problem with pip.
3.834
3.834 [notice] A new release of pip is available: 23.0.1 -> 24.0
3.834 [notice] To update, run: pip install --upgrade pip
------

**Comment by orion-satyammishra** [comment]
Thanks for reading!

I cloned the few days before It was working fine then, today I am getting error.
Can you please help so that previous version

Thanks

**Comment by prateeksachan** [comment]
hey @orion-satyammishra can you please update with latest code and try again?

**Comment by orion-satyammishra** [comment]
I have tried multiple times, even removing cloning again, its same.

**Comment by orion-satyammishra** [comment]
=> ERROR [bolna-app  8/14] RUN pip install --force-reinstall git+https://github.com/bolna-ai/bolna@master        5.2s
------
 > [bolna-app  8/14] RUN pip install --force-reinstall git+https://github.com/bolna-ai/bolna@master:
0.277 Collecting git+https://github.com/bolna-ai/bolna@master
0.277   Cloning https://github.com/bolna-ai/bolna (to revision master) to /tmp/pip-req-build-s7sywjnk
0.280   Running command git clone --filter=blob:none --quiet https://github.com/bolna-ai/bolna /tmp/pip-req-build-s7sywjnk
2.659   Resolved https://github.com/bolna-ai/bolna to commit c4d91fd9eca5490d55550a7f31bfe4b4b73d94ea
2.665   Installing build dependencies: started
4.991   Installing build dependencies: finished with status 'done'
4.992   Getting requirements to build wheel: started
5.129   Getting requirements to build wheel: finished with status 'error'
5.133   error: subprocess-exited-with-error
5.133
5.133   × Getting requirements to build wheel did not run successfully.
5.133   │ exit code: 1
5.133   ╰─> [52 lines of output]
5.133       Traceback (most recent call last):
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
5.133           parsed = _parse_requirement(requirement_string)
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
5.133           return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
5.133           url, specifier, marker = _parse_requirement_details(tokenizer)
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
5.133           marker = _parse_requirement_marker(
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
5.133           tokenizer.raise_syntax_error(
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
5.133           raise ParserSyntaxError(
5.133       setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
5.133           git+https://github.com/qdrant/fastembed@main
5.133              ^
5.133
5.133       The above exception was the direct cause of the following exception:
5.133
5.133       Traceback (most recent call last):
5.133         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
5.133           main()
5.133         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
5.133           json_out['return_val'] = hook(**hook_input['kwargs'])
5.133         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
5.133           return hook(config_settings)
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
5.133           return self._get_build_requires(config_settings, requirements=['wheel'])
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
5.133           self.run_setup()
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
5.133           exec(code, locals())
5.133         File "<string>", line 1, in <module>
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
5.133           return distutils.core.setup(**attrs)
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 158, in setup
5.133           dist.parse_config_files()
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 631, in parse_config_files
5.133           pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 69, in apply_configuration
5.133           return _apply(dist, config, filepath)
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 63, in apply
5.133           dist._finalize_requires()
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 368, in _finalize_requires
5.133           self._normalize_requires()
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 383, in _normalize_requires
5.133           self.install_requires = list(map(str, _reqs.parse(install_requires)))
5.133         File "/tmp/pip-build-env-mkfosif4/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
5.133           raise InvalidRequirement(str(e)) from e
5.133       setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
5.133           git+https://github.com/qdrant/fastembed@main
5.133              ^
5.133       [end of output]
5.133
5.133   note: This error originates from a subprocess, and is likely not a problem with pip.
5.134 error: subprocess-exited-with-error
5.134
5.134 × Getting requirements to build wheel did not run successfully.
5.134 │ exit code: 1
5.134 ╰─> See above for output.
5.134
5.134 note: This error originates from a subprocess, and is likely not a problem with pip.
5.135
5.135 [notice] A new release of pip is available: 23.0.1 -> 24.0
5.135 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip install --force-reinstall git+https://github.com/bolna-ai/bolna@master" did not complete successfully: exit code: 1

**Comment by prateeksachan** [comment]
thanks for reporting this and sending over the logs. Will check this and let you know @orion-satyammishra

**Comment by prateeksachan** [comment]
@orion-satyammishra there were a few changes which I made wrt package versions in https://github.com/bolna-ai/bolna/pull/131. Should work now.

```
 => [bolna-app  7/14] RUN pip install -r requirements.txt                                                                                                                                              6.9s
 => [bolna-app  8/14] RUN pip install --force-reinstall git+https://github.com/bolna-ai/bolna@master                                                                                                  34.3s
 => [bolna-app  9/14] RUN pip install scipy==1.11.0                                                                                                                                                    6.6s
 => [bolna-app 10/14] RUN pip install torch==2.0.1                                                                                                                                                    11.9s
 => [bolna-app 11/14] RUN pip install torchaudio==2.0.1                                                                                                                                               14.2s
 => [bolna-app 12/14] RUN pip install pydub==0.25.1                                                                                                                                                    0.7s
 => [bolna-app 13/14] RUN pip install ffprobe                                                                                                                                                          1.4s
 => [bolna-app 14/14] RUN pip install aiofiles                                                                                                                                                         0.6s
 => [bolna-app] exporting to image                                                                                                                                                                     2.8s
 => => exporting layers                                                                                                                                                                                2.8s
 => => writing image sha256:60e73912a95a89bb054ec621da9910afe0d7c2bebe3629889e7161c7ad9db9da                                                                                                           0.0s
 => => naming to docker.io/library/local_setup-bolna-app                                                                                                                                               0.0s
[+] Running 5/5
 ✔ Network local_setup_default         Created                                                                                                                                                         0.1s
 ✔ Container local_setup-ngrok-1       Created                                                                                                                                                         0.2s
 ✔ Container local_setup-redis-1       Created                                                                                                                                                         0.2s
 ✔ Container local_setup-bolna-app-1   Created                                                                                                                                                         0.0s
 ✔ Container local_setup-twilio-app-1  Created
```

**Comment by orion-satyammishra** [comment]
thank you @prateeksachan  it worked!
