### ISSUE TITLE
Add Plivo support for telephony as it supports both US and India for phone numbers and outbound calling

### ISSUE THREAD

**Issue by bevenky** [voxos-ai/bolna#148]

**Comment by prateeksachan** [comment]
Hey @bevenky, we've documented the approach to add telephony providers in readme: https://github.com/bolna-ai/bolna?tab=readme-ov-file#extending-with-other-telephony-providers

For reference, you may check out Twilio/Exotel integrations (assuming Plivo's would be similar and supporting similar events/packets): https://github.com/bolna-ai/bolna/tree/master/bolna/output_handlers/telephony_providers

**Comment by prateeksachan** [comment]
hey @bevenky , was trying to integrate with plivo but wasn't sure on how to stream outbound calls. have reached out to your support team for this.

example gist: https://gist.github.com/prateeksachan/816cfe1e8416e86d08980026a7eee7e8

**Comment by chrigui** [comment]
> hey @bevenky , was trying to integrate with plivo but wasn't sure on how to stream outbound calls. have reached out to your support team for this.
> 
> example gist: https://gist.github.com/prateeksachan/816cfe1e8416e86d08980026a7eee7e8

Have you managed to fix the stream outbound calls ?

**Comment by prateeksachan** [comment]
hey @chrigui , we managed to stream an outbound call using plivo. Will push the PR in the next couple of hours.

**Comment by chrigui** [comment]
> hey @chrigui , we managed to stream an outbound call using plivo. Will push the PR in the next couple of hours.

Glad it worked out, Looking forward to it. Thank you

**Comment by prateeksachan** [comment]
Hey @bevenky , I have now integrated plivo as part of https://github.com/bolna-ai/bolna/pull/157 but facing an issue where a 2nd `/post_callback` is triggered opening up another websocket connection just after the initial call is finished. Have reached out to the support. 

plivo code for triggering the API call and streaming an outbound call over websocket:
https://github.com/bolna-ai/bolna/blob/83c04f1ec826b66c33830d2f3b2d63d88b7fb61e/local_setup/telephony_server/plivo_api_server.py#L49-L99

Related logs:
```
wss://cd72-2405-201-4012-a2-e981-d67a-f4e6-fec6.ngrok-free.app/chat/v1/f22b5780-3261-46a2-a2f0-21d029ed0f48
INFO:     18.136.128.252:0 - "POST /plivo_callback?ws_url=wss://cd72-2405-201-4012-a2-e981-d67a-f4e6-fec6.ngrok-free.app&agent_id=f22b5780-3261-46a2-a2f0-21d029ed0f48 HTTP/1.1" 200 OK
wss://cd72-2405-201-4012-a2-e981-d67a-f4e6-fec6.ngrok-free.app/chat/v1/f22b5780-3261-46a2-a2f0-21d029ed0f48
INFO:     18.136.128.252:0 - "POST /plivo_callback?ws_url=wss://cd72-2405-201-4012-a2-e981-d67a-f4e6-fec6.ngrok-free.app&agent_id=f22b5780-3261-46a2-a2f0-21d029ed0f48 HTTP/1.1" 200 OK
```

**Comment by prateeksachan** [comment]
hey @bevenky this is now merged and integrated. However, streaming audio chunks back to Plivo isn't working and hence there's a limitation to interruption handling during conversations. If someone from Plivo can check - it would be great!

https://github.com/bolna-ai/bolna/blob/00f3ca08d63cc2415c7f40e97e53d76b57b74926/README.md?plain=1#L205-L211


Additionally, if there's any official Plivo blog to setup a Trial account we can add the link here:
https://github.com/bolna-ai/bolna/blob/b160e7cccb6d041c869b8831536f017d418bbb05/README.md?plain=1#L50-L52

**Comment by prateeksachan** [comment]
Closing this now. Plivo will be releasing improvements which might enable interruptions in couple of days. We can pick it up when it goes GA.
