### ISSUE TITLE
Error: " NameError: name 'WhisperTranscriber' is not defined" 

### ISSUE THREAD

**Issue by orion-satyammishra** [voxos-ai/bolna#166]
Getting following error after build and compose-up

bolna-app-1   | Traceback (most recent call last):
bolna-app-1   |   File "/usr/local/bin/uvicorn", line 8, in <module>
bolna-app-1   |     sys.exit(main())
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
bolna-app-1   |     return self.main(*args, **kwargs)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
bolna-app-1   |     rv = self.invoke(ctx)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
bolna-app-1   |     return ctx.invoke(self.callback, **ctx.params)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
bolna-app-1   |     return __callback(*args, **kwargs)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
bolna-app-1   |     run(
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
bolna-app-1   |     server.run()
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
bolna-app-1   |     return asyncio.run(self.serve(sockets=sockets))
bolna-app-1   |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
bolna-app-1   |     return loop.run_until_complete(main)
bolna-app-1   |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
bolna-app-1   |     config.load()
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
bolna-app-1   |     self.loaded_app = import_from_string(self.app)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
bolna-app-1   |     module = importlib.import_module(module_str)
bolna-app-1   |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
bolna-app-1   |     return _bootstrap._gcd_import(name[level:], package, level)
bolna-app-1   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
bolna-app-1   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
bolna-app-1   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
bolna-app-1   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
bolna-app-1   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
bolna-app-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
bolna-app-1   |   File "/app/quickstart_server.py", line 12, in <module>
bolna-app-1   |     from bolna.models import *
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/models.py", line 4, in <module>
bolna-app-1   |     from .providers import *
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/providers.py", line 17, in <module>
bolna-app-1   |     'whisper': WhisperTranscriber #Seperate out a transcriber for https://github.com/bolna-ai/streaming-transcriber-server or build a deepgram compatible proxy
bolna-app-1   | NameError: name 'WhisperTranscriber' is not defined
bolna-app-1 exited with code 1

**Comment by marmikcfc** [comment]
Hey Satyam, can you confirm you have the latest pull? 
I have integrated Whisper in - #165

**Comment by orion-satyammishra** [comment]
Now this is fixed.
