### ISSUE TITLE
SUPPORTED_LLM_MODELS variable miss used, please check

### ISSUE THREAD

**Issue by satyam-mishra-ai** [voxos-ai/bolna#174]
def __setup_llm(self, llm_config):
        if self.task_config["tools_config"]["llm_agent"] is not None:
            if self.task_config["tools_config"]["llm_agent"]["family"] in SUPPORTED_LLM_MODELS.keys():
                llm_class = SUPPORTED_LLM_MODELS.get(self.task_config["tools_config"]["llm_agent"]["family"])
                logger.info(f"LLM CONFIG {llm_config}")
                llm = llm_class(**llm_config, **self.kwargs)
                return llm
            else:
                raise Exception(f'LLM {self.task_config["tools_config"]["llm_agent"]["family"]} not supported')

**Comment by satyam-mishra-ai** [comment]
It should be SUPPORTED_LLM_PROVIDERS

**Comment by prateeksachan** [comment]
hey @7990satyam200 AFAIK, we had fixed this sometime back.

https://github.com/bolna-ai/bolna/blob/192d0892ef0c32a0624851dda782d9f1c4d29010/bolna/agent_manager/task_manager.py#L380-L389

**Comment by satyam-mishra-ai** [comment]
sorry
