### ISSUE TITLE
 LiteLLM.__init__() missing 1 required positional argument: 'model'

### ISSUE THREAD

**Issue by orion-satyammishra** [voxos-ai/bolna#175]
bolna-app-1   |   File "/app/quickstart_server.py", line 53, in create_agent
bolna-app-1   |     extraction_prompt_generation_llm = LiteLLM(streaming_model=extraction_prompt_llm, max_tokens=2000)
bolna-app-1   | TypeError: LiteLLM.__init__() missing 1 required positional argument: 'model'

**Comment by prateeksachan** [comment]
thanks for reporting this @orion-satyammishra . will check and push the required fix.

**Comment by prateeksachan** [comment]
fixed in [cb97556](https://github.com/bolna-ai/bolna/pull/176/commits/cb975561e5331f653d459f57c633fbad11056a62).
