### ISSUE TITLE
Standarize open ai llm response_format based on models passed

### ISSUE THREAD

**Issue by prateeksachan** [voxos-ai/bolna#22]
Should check for the model passed is compatible with the response_format
Only compatible models/response_format should be passed to openai SDK

https://github.com/bolna-ai/bolna/blob/96004ecd14d94ce4bc79170d1d5a516298ffe0fc/agents/llms/openai_llm.py#L23-L32

https://github.com/bolna-ai/bolna/blob/96004ecd14d94ce4bc79170d1d5a516298ffe0fc/agents/llms/openai_llm.py#L53-L58

**Comment by sachanayush47** [comment]
I think this bug has been resolved.

**Comment by prateeksachan** [comment]
Hi @sachanayush47 , yes this was resolved as part of https://github.com/bolna-ai/bolna/pull/42.
