### ISSUE TITLE
Typo in telephony dockerfiles

### ISSUE THREAD

**Issue by satvikreddy** [voxos-ai/bolna#230]
**Expectation:**
twilio: 8001
plivo: 8002

but dockerfiles have reverse

![image](https://github.com/bolna-ai/bolna/assets/16370824/c7e4fe2e-8132-45fb-8c9b-3f3ade99ba84)

![image](https://github.com/bolna-ai/bolna/assets/16370824/226a46e4-894f-44d2-8164-342ab8772cda)

![image](https://github.com/bolna-ai/bolna/assets/16370824/d8075678-693d-45e0-951b-bc5650fd1963)

**Comment by prateeksachan** [comment]
thanks for reporting this @satvikreddy  . this is now fixed in 2226067414e7885b7cd400b58a6ad5a953842160

**Comment by satvikreddy** [comment]
@prateeksachan even 'expose' needs to be changed.

**Comment by prateeksachan** [comment]
Good catch @satvikreddy . Have fixed this too as part of bea2857bca64e5069ca6e84fa68ce3974135b3c3
