### ISSUE TITLE
Please add Plivo lib in local setup requirement.txt

### ISSUE THREAD

**Issue by satishBohra** [voxos-ai/bolna#250]
Here's the corrected version of your text:

1. Add the Plivo library to `requirements.txt`:
   ```
   plivo==4.55.0
   ```

2. Add the `keepalive` parameter to Plivo to stay connected. For example:
   ```xml
   <Stream bidirectional="true" keepCallAlive="true">{}</Stream>
   ```

3. I am still not getting any output. Please update the code.

**Comment by prateeksachan** [comment]
hey @satishBohra, have added this in the `local_setup` directory so it's available in the docker. ref: 7f665d4193ae364006a2b5c4f9fbb9e021bfe873. do let me know in case of any issues.

**Comment by satishBohra** [comment]
Thanks
