### ISSUE TITLE
Exception: Something went wrong while sending heartbeats to deepgram bolna-

### ISSUE THREAD

**Issue by orion-satyammishra** [voxos-ai/bolna#251]
bolna-app-1   | 2024-06-17 08:19:23.514 ERROR {traceback} [extract] Task exception was never retrieved
bolna-app-1   | future: <Task finished name='Task-31' coro=<DeepgramTranscriber.send_heartbeat() done, defined at /usr/local/lib/python3.10/site-packages/bolna/transcriber/deepgram_transcriber.py:112> exception=Exception('Something went wrong while sending heartbeats to deepgram') created at /usr/local/lib/python3.10/asyncio/tasks.py:337>
bolna-app-1   | source_traceback: Object created at (most recent call last):
bolna-app-1   |   File "/usr/local/bin/uvicorn", line 8, in <module>
bolna-app-1   |     sys.exit(main())
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
bolna-app-1   |     return self.main(*args, **kwargs)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
bolna-app-1   |     rv = self.invoke(ctx)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
bolna-app-1   |     return ctx.invoke(self.callback, **ctx.params)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
bolna-app-1   |     return __callback(*args, **kwargs)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
bolna-app-1   |     run(
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
bolna-app-1   |     server.run()
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
bolna-app-1   |     return asyncio.run(self.serve(sockets=sockets))
bolna-app-1   |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
bolna-app-1   |     return loop.run_until_complete(main)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/transcriber/deepgram_transcriber.py", line 353, in transcribe
bolna-app-1   |     self.heartbeat_task = asyncio.create_task(self.send_heartbeat(deepgram_ws))
bolna-app-1   |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 337, in create_task
bolna-app-1   |     task = loop.create_task(coro)
bolna-app-1   | Traceback (most recent call last):
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/transcriber/deepgram_transcriber.py", line 116, in send_heartbeat
bolna-app-1   |     await ws.send(json.dumps(data))
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
bolna-app-1   |     await self.ensure_open()
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
bolna-app-1   |     raise self.connection_closed_exc()
bolna-app-1   | websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
bolna-app-1   |
bolna-app-1   | During handling of the above exception, another exception occurred:
bolna-app-1   |
bolna-app-1   | Traceback (most recent call last):
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/transcriber/deepgram_transcriber.py", line 120, in send_heartbeat
bolna-app-1   |     raise Exception("Something went wrong while sending heartbeats to {}".format(self.model))
bolna-app-1   | Exception: Something went wrong while sending heartbeats to deepgram
bolna-

**Comment by marmikcfc** [comment]
Hey this happens sometimes when we close the connection but before the connection is fully closed, heartbeat coroutine wakes up and tries to send the heartbeat
