### ISSUE TITLE
Try changing twilio API to twiML for triggering calls

### ISSUE THREAD

**Issue by prateeksachan** [voxos-ai/bolna#27]
USe TwiML here to see if it gives a better success rate

https://github.com/bolna-ai/bolna/blob/f342fff82655933adfc7f5c7abc11cc05e816de1/local_setup/telephony_server/twilio_api_server.py#L96-L105

**Comment by mdehsan873** [comment]
@prateeksachan Hi , can i contribute this repo ?

**Comment by prateeksachan** [comment]
Hey @mdehsan873 sure! you may fork the repo and raise the PR. let me know if you need any help.

**Comment by prateeksachan** [comment]
Not required; current implementation works!
