### ISSUE TITLE
when install through docker error in bolna dockerfile

### ISSUE THREAD

**Issue by tonyMilad** [voxos-ai/bolna#281]
gives error on RUN pip install --force-reinstall git+https://github.com/bolna-ai/bolna@StyleTTS

**Comment by marmikcfc** [comment]
Can you try installing the master branch instead styletts
 It has already been merged into master.

**Comment by tonyMilad** [comment]
i have already installing from the master but in local_setup -->  dockerfiles --> bolna _server.dockerfile in line 10 
"RUN pip install --force-reinstall git+https://github.com/bolna-ai/bolna@StyleTTS"
give error when build through docker-compase.yml

**Comment by marmikcfc** [comment]
Instead of git+https://github.com/bolna-ai/bolna@StyleTTS can you try git+https://github.com/bolna-ai/bolna@master?

**Comment by tonyMilad** [comment]
yes it worked 
but when I run docker-compose up
.env file not found because it's not located on locat_setup 
I think .env file should be located in local_setup also

**Comment by orion-satyammishra** [comment]
yes .env is required in local_setup

**Comment by prateeksachan** [comment]
Hello @tonyMilad . Thanks for reporting this. Will get it fixed in the next couple of hours.

**Comment by prateeksachan** [comment]
hey @tonyMilad this was fixed. please check and let me know it's working fine for you now.
