### ISSUE TITLE
chore: UnOptimized Dockerfiles in local_setup

### ISSUE THREAD

**Issue by h3110Fr13nd** [voxos-ai/bolna#355]
- [x] Improper requirements file
- [x] Not utilising build cache as requirements are is copied after or with the whole app
- [x] Unnecessarily increased number of Layers
- [x] Changes in quickstart_server app will require to download and install the pip dependencies again.

**Comment by h3110Fr13nd** [comment]
I'm already working on this Issue.

Can you assign this to me?

**Comment by prateeksachan** [comment]
hey @h3110Fr13nd any updates here?

**Comment by h3110Fr13nd** [comment]
I've tried and tested it.
If you want to Test it before Merging the PR
Then you'll have to make a fork and make a change in `bolna_server.Dockerfile`
```Dockerfile
FROM python:3.10.13-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    git \
    ffmpeg
# NOTE: Change the username and repo name to your fork
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install git+https://github.com/<your-username>/<your-fork-bolna>@master

COPY quickstart_server.py /app/
EXPOSE 5001
CMD ["uvicorn", "quickstart_server:app", "--host", "0.0.0.0", "--port", "5001"]
```
This step is required as torchaudio isn't originally in master of bolna requirements.

**Comment by h3110Fr13nd** [comment]
Tell me if any suggestion or changes required.

**Comment by prateeksachan** [comment]
thanks @h3110Fr13nd for this PR. Will test it out and merge it today.
