### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by MustaphaU** [voxos-ai/bolna#50]
Hi,

Just a quick one: not sure where this error is coming from: 

```ImportError: cannot import name 'CustomLogger' from 'bolna.helpers.logger_config' (/usr/local/lib/python3.10/site-packages/bolna/helpers/logger_config.py)```

I had renamed the `config_logger` function in logger_config.py to `CustomLogger` but the issue persists.

I would appreciate your help!

**Comment by prateeksachan** [comment]
@MustaphaU do you have the latest master? There was a small typo which we fixed recently.

**Comment by MustaphaU** [comment]
> @MustaphaU do you have the latest master? There was a small typo which we fixed recently.

@prateeksachan  I am not sure. I will try using the latest to see if the issue resolves.

**Comment by prateeksachan** [comment]
@MustaphaU sure, do let me know. In case it doesn't please feel free to mark a time https://calendly.com/bolna/30min. We can go over it on a call. Thanks.

**Comment by MustaphaU** [comment]
Thanks @prateeksachan It worked but now there is a new issue. I am unable to create an agent. How do I get the bearer token? 
![image](https://github.com/bolna-ai/bolna/assets/123378149/4a1191a5-8998-42e2-ba10-b366085571e6)

**Comment by prateeksachan** [comment]
@MustaphaU , we're still in beta for the hosting solution for which you require the API keys for bearer auth. It would require couple of weeks for releasing it in GA. Once, that is done, you can have the api keys.

For now, this repo is open-sourced which you can use to create & build agents as per your use case without any api keys. For anything speific, feel free to discuss over a call. thanks.
